"""Test Submission — generated by commonsc-devkit init.

Edit the GENOTYPES table to add real interpretations, then run:
    commonsc-devkit validate <project-dir>
"""
from __future__ import annotations

import time
from typing import Any

ID = "druidalabs/test-submission"
RSID = "rs1234567"

# Map a normalized two-letter genotype (sorted alleles — `AG`, never `GA`) to
# its human-readable interpretation. Tone is one of `moss`, `amber`, `rust`,
# `neutral` — drives the result card's accent colour.
GENOTYPES: dict[str, dict[str, Any]] = {
    # "AA": {"summary": "AA — TODO short headline", "detail": "TODO longer explanation.", "tone": "moss"},
    # "AG": {"summary": "AG — TODO short headline", "detail": "TODO longer explanation.", "tone": "moss"},
    # "GG": {"summary": "GG — TODO short headline", "detail": "TODO longer explanation.", "tone": "amber"},
}


def _norm(geno: str) -> str:
    if len(geno) != 2:
        return geno
    return "".join(sorted(geno))


def compute(variant_set: dict[str, Any]) -> dict[str, Any]:
    """Single-variant lookup entry point.

    Receives a VariantSet (genomic-io.schema.json#/$defs/VariantSet) and
    returns a Result envelope (result.schema.json#/$defs/Result).
    """
    variants = {v["rsid"]: v for v in variant_set.get("variants", [])}
    v = variants.get(RSID)
    base = {
        "schemaVersion": "1",
        "algorithmId": ID,
        "algorithmVersion": "0.1.0",
        "computedAt": int(time.time() * 1000),
    }

    if v is None:
        return {
            **base,
            "summary": f"{RSID} was not called in this file",
            "tone": "amber",
            "unavailable": f"{RSID} not present in this sample.",
            "blocks": [],
        }

    geno = _norm(v["genotype"])
    interp = GENOTYPES.get(geno) or GENOTYPES.get(v["genotype"]) or None
    if interp is None:
        return {
            **base,
            "summary": f"{v['genotype']} — unrecognised genotype",
            "tone": "amber",
            "detail": "Edit GENOTYPES in main.py to map this genotype to an interpretation.",
            "blocks": [],
        }

    return {
        **base,
        "summary": interp["summary"],
        "detail": interp.get("detail"),
        "tone": interp.get("tone", "moss"),
        "blocks": [
            {
                "kind": "rows",
                "title": "Variant",
                "rows": [
                    {"label": "rsID", "value": RSID},
                    {"label": "Genotype", "value": v["genotype"]},
                    {"label": "Chromosome", "value": f"chr{v['chrom']}"},
                ],
            }
        ],
    }
