//! Scaffold a new algorithm project.
//!
//! `commonsc-devkit init` produces a working starting point: a manifest
//! template pre-filled with the supplied identity, a Python entrypoint with a
//! single-variant lookup skeleton, a synthetic fixture conforming to the
//! VariantSet schema, and a README pointing at the next steps. The author
//! fills in the genotype interpretations and runs `validate` to confirm the
//! scaffold passes the local gates before publishing.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use serde_json::{json, Value};

pub struct InitOptions {
    pub dir: PathBuf,
    pub id: String,
    pub name: Option<String>,
    pub blurb: String,
    pub category: String,
    pub rsid: Option<String>,
    pub publisher_handle: Option<String>,
    pub publisher_name: String,
}

pub struct InitSummary {
    pub dir: PathBuf,
    pub package_name: String,
}

impl InitSummary {
    pub fn print(&self) {
        println!("scaffolded {}", self.dir.display());
        println!("  package: {}", self.package_name);
        println!("  next steps:");
        println!("    1. fill in `compute()` in {}/main.py", self.package_name);
        println!("    2. flesh out fixtures/input.json with a realistic VariantSet");
        println!("    3. cargo run -p commonsc-devkit -- validate {}", self.dir.display());
        println!("    4. cargo run -p commonsc-devkit -- publish  {}", self.dir.display());
    }
}

pub fn run(opts: InitOptions) -> Result<InitSummary> {
    if opts.dir.exists() {
        return Err(anyhow!(
            "{} already exists — pick a fresh directory or remove it first",
            opts.dir.display()
        ));
    }

    let (publisher_slug, algo_slug) = split_id(&opts.id)?;
    let publisher_handle = opts
        .publisher_handle
        .clone()
        .unwrap_or_else(|| publisher_slug.clone());
    let package_name = slug_to_python(&algo_slug);
    let display_name = opts.name.clone().unwrap_or_else(|| title_case(&algo_slug));
    let category = validate_category(&opts.category)?;
    let rsid = opts.rsid.unwrap_or_else(|| "rs1234567".to_string());
    let key_id = format!("{publisher_handle}-2026-01");

    fs::create_dir_all(&opts.dir)
        .with_context(|| format!("creating project dir {}", opts.dir.display()))?;

    // ── manifest.template.json ─────────────────────────────────────────────
    let manifest = build_manifest(BuildManifest {
        id: &opts.id,
        name: &display_name,
        blurb: &opts.blurb,
        category: &category,
        package: &package_name,
        rsid: &rsid,
        publisher_handle: &publisher_handle,
        publisher_name: &opts.publisher_name,
        key_id: &key_id,
    });
    let manifest_text = serde_json::to_string_pretty(&manifest)? + "\n";
    fs::write(opts.dir.join("manifest.template.json"), manifest_text)
        .context("writing manifest.template.json")?;

    // ── Python entrypoint package ──────────────────────────────────────────
    let package_dir = opts.dir.join(&package_name);
    fs::create_dir_all(&package_dir).context("creating Python package directory")?;
    fs::write(
        package_dir.join("__init__.py"),
        format!("\"\"\"{display_name} — generated by commonsc-devkit init.\"\"\"\n"),
    )
    .context("writing __init__.py")?;
    fs::write(
        package_dir.join("main.py"),
        render_main_py(&opts.id, &rsid, &display_name),
    )
    .context("writing main.py")?;

    // ── Synthetic fixture ──────────────────────────────────────────────────
    fs::create_dir_all(opts.dir.join("fixtures")).context("creating fixtures directory")?;
    let fixture = json!({
        "referenceBuild": "GRCh38",
        "fileKind": "23andme",
        "sampleId": format!("fixture-{package_name}"),
        "variants": [
            { "rsid": rsid, "chrom": "1", "position": 1, "genotype": "AA" },
        ],
    });
    fs::write(
        opts.dir.join("fixtures/input.json"),
        serde_json::to_string_pretty(&fixture)? + "\n",
    )
    .context("writing fixtures/input.json")?;

    // ── README ────────────────────────────────────────────────────────────
    fs::write(opts.dir.join("README.md"), render_readme(&opts.id, &display_name, &package_name))
        .context("writing README.md")?;

    Ok(InitSummary {
        dir: opts.dir,
        package_name,
    })
}

struct BuildManifest<'a> {
    id: &'a str,
    name: &'a str,
    blurb: &'a str,
    category: &'a str,
    package: &'a str,
    rsid: &'a str,
    publisher_handle: &'a str,
    publisher_name: &'a str,
    key_id: &'a str,
}

fn build_manifest(b: BuildManifest<'_>) -> Value {
    json!({
        "schemaVersion": "2",
        "id": b.id,
        "version": "0.1.0",
        "name": b.name,
        "blurb": b.blurb,
        "license": "Apache-2.0",
        "category": b.category,
        "tier": "pyodide",
        "entrypoint": {
            "module": format!("{}.main", b.package),
            "function": "compute",
        },
        "lockfile": {
            "interpreter": { "name": "pyodide", "version": "0.26.2" },
            "dependencies": []
        },
        "capabilities": {
            "network": false,
            "fsRead": ["/input"],
            "fsWrite": ["/output"],
            "progress": false
        },
        "input": {
            "schemaRef": "genomic-io.schema.json#/$defs/VariantSet",
            "referenceBuild": "GRCh38"
        },
        "output": {
            "schemaRef": "result.schema.json#/$defs/Result"
        },
        "supportedKinds": ["23andme", "ancestry", "myheritage", "livingdna", "vcf", "vcf-gz"],
        "requirements": {
            "memoryMiB": 128,
            "wallSeconds": 10,
            "diskMiB": 4
        },
        "publisher": {
            "handle": b.publisher_handle,
            "name": b.publisher_name,
            "url": "https://commonsc.io",
            "keyId": b.key_id,
        },
        "sourceUrl": format!("https://github.com/commonsc/algorithms/tree/main/{}", b.package),
    })
}

fn render_main_py(id: &str, rsid: &str, name: &str) -> String {
    format!(
        r#""""{name} — generated by commonsc-devkit init.

Edit the GENOTYPES table to add real interpretations, then run:
    commonsc-devkit validate <project-dir>
"""
from __future__ import annotations

import time
from typing import Any

ID = "{id}"
RSID = "{rsid}"

# Map a normalized two-letter genotype (sorted alleles — `AG`, never `GA`) to
# its human-readable interpretation. Tone is one of `moss`, `amber`, `rust`,
# `neutral` — drives the result card's accent colour.
GENOTYPES: dict[str, dict[str, Any]] = {{
    # "AA": {{"summary": "AA — TODO short headline", "detail": "TODO longer explanation.", "tone": "moss"}},
    # "AG": {{"summary": "AG — TODO short headline", "detail": "TODO longer explanation.", "tone": "moss"}},
    # "GG": {{"summary": "GG — TODO short headline", "detail": "TODO longer explanation.", "tone": "amber"}},
}}


def _norm(geno: str) -> str:
    if len(geno) != 2:
        return geno
    return "".join(sorted(geno))


def compute(variant_set: dict[str, Any]) -> dict[str, Any]:
    """Single-variant lookup entry point.

    Receives a VariantSet (genomic-io.schema.json#/$defs/VariantSet) and
    returns a Result envelope (result.schema.json#/$defs/Result).
    """
    variants = {{v["rsid"]: v for v in variant_set.get("variants", [])}}
    v = variants.get(RSID)
    base = {{
        "schemaVersion": "1",
        "algorithmId": ID,
        "algorithmVersion": "0.1.0",
        "computedAt": int(time.time() * 1000),
    }}

    if v is None:
        return {{
            **base,
            "summary": f"{{RSID}} was not called in this file",
            "tone": "amber",
            "unavailable": f"{{RSID}} not present in this sample.",
            "blocks": [],
        }}

    geno = _norm(v["genotype"])
    interp = GENOTYPES.get(geno) or GENOTYPES.get(v["genotype"]) or None
    if interp is None:
        return {{
            **base,
            "summary": f"{{v['genotype']}} — unrecognised genotype",
            "tone": "amber",
            "detail": "Edit GENOTYPES in main.py to map this genotype to an interpretation.",
            "blocks": [],
        }}

    return {{
        **base,
        "summary": interp["summary"],
        "detail": interp.get("detail"),
        "tone": interp.get("tone", "moss"),
        "blocks": [
            {{
                "kind": "rows",
                "title": "Variant",
                "rows": [
                    {{"label": "rsID", "value": RSID}},
                    {{"label": "Genotype", "value": v["genotype"]}},
                    {{"label": "Chromosome", "value": f"chr{{v['chrom']}}"}},
                ],
            }}
        ],
    }}
"#,
        id = id,
        rsid = rsid,
        name = name,
    )
}

fn render_readme(id: &str, name: &str, package: &str) -> String {
    format!(
        r#"# {name}

`{id}` — scaffolded by `commonsc-devkit init`.

## What to edit

- `{package}/main.py` — fill the `GENOTYPES` table with real interpretations
  per genotype. Tone values (`moss`, `amber`, `rust`, `neutral`) drive the
  result card colour.
- `manifest.template.json` — confirm the blurb, category, and `supportedKinds`
  match what the algorithm actually does. Bump `version` for every change once
  you've published the first cut.
- `fixtures/input.json` — adjust the genotype on the placeholder variant so
  validation exercises an interpretation path you care about.

## Workflow

```sh
# Verify the scaffold passes the local gates (manifest schema, entrypoint
# import, fixture conforms to VariantSet).
cargo run -p commonsc-devkit -- validate <this-dir>

# Bundle, sign with the dev keys, and write into commonsc/registry/.
cargo run -p commonsc-devkit -- publish <this-dir>
```

After publish, the customer app picks up the new algorithm on the next catalog
pull. Bumping `version` and re-publishing produces an "update available" pill
on the installed tile.
"#,
        id = id,
        name = name,
        package = package,
    )
}

fn split_id(id: &str) -> Result<(String, String)> {
    let mut parts = id.splitn(2, '/');
    let publisher = parts
        .next()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| anyhow!("manifest id missing publisher prefix (expected `publisher/name`)"))?;
    let algo = parts
        .next()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| anyhow!("manifest id missing algorithm name after `/`"))?;
    if !is_kebab(publisher) || !is_kebab(algo) {
        return Err(anyhow!(
            "manifest id `{id}` must match `[a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]*`"
        ));
    }
    Ok((publisher.to_string(), algo.to_string()))
}

fn is_kebab(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    let bytes = s.as_bytes();
    if !(bytes[0].is_ascii_lowercase() || bytes[0].is_ascii_digit()) {
        return false;
    }
    bytes
        .iter()
        .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || *b == b'-')
}

fn slug_to_python(s: &str) -> String {
    s.replace('-', "_")
}

fn title_case(slug: &str) -> String {
    slug.split('-')
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn validate_category(c: &str) -> Result<String> {
    match c {
        // Atlas regions (consumer-facing groupings) + supporting categories.
        // "trait" kept for back-compat with manifests pre-atlas-rename.
        "appearance" | "senses" | "fuel" | "motion" | "wellness" | "quality"
        | "ancestry" | "risk" | "research" | "trait" => Ok(c.to_string()),
        _ => Err(anyhow!(
            "invalid category `{c}` (expected one of appearance, senses, fuel, motion, wellness, quality, ancestry, risk, research)"
        )),
    }
}

#[allow(dead_code)]
fn ensure_dir_does_not_exist(dir: &Path) -> Result<()> {
    if dir.exists() {
        return Err(anyhow!("{} already exists", dir.display()));
    }
    Ok(())
}
